services:
  - type: web
    name: space-invaders-remastered
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RACK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 2