services:
  - type: web
    name: space-invaders
    env: ruby
    plan: free
    region: oregon
    buildCommand: bundle install
    startCommand: bundle exec puma -b tcp://0.0.0.0:$PORT config.ru
    envVars:
      - key: RACK_ENV
        value: production